import { addDays, subDays } from 'date-fns';

const today = new Date();

export const events = [
  {
    id: 1,
    name: 'Summer Classic 2024',
    startDate: today,
    endDate: addDays(today, 2),
    location: 'Lexington, KY',
    association: 'AQHA',
    status: 'live',
    viewers: 1247,
    currentClass: 'Open Western Pleasure Finals',
    website: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1595872018818-97555653a011?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
    patternBook: {
      id: 1,
      isLive: true,
      publishDate: subDays(today, 1),
    },
    totalEntries: 234,
    totalPrizes: '$50,000',
    classes: [
      { name: 'Open Western Pleasure', time: '9:00 AM', ring: 'Ring 1', entries: 24 },
      { name: 'Amateur Horsemanship', time: '10:30 AM', ring: 'Ring 2', entries: 18 },
      { name: 'Youth Reining', time: '1:00 PM', ring: 'Ring 1', entries: 15 },
    ],
  },
  {
    id: 2,
    name: 'Youth Regional Championships',
    startDate: today,
    endDate: addDays(today, 3),
    location: 'Ocala, FL',
    association: 'NSBA',
    status: 'live',
    viewers: 892,
    currentClass: 'Youth Hunter Under Saddle 14-18',
    website: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1569587889770-9134d27b292e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
    patternBook: {
      id: 2,
      isLive: true,
      publishDate: subDays(today, 2),
    },
    totalEntries: 188,
    totalPrizes: '$30,000',
    classes: [
      { name: 'Youth Hunter Under Saddle', time: '8:30 AM', ring: 'Hunter Arena', entries: 22 },
      { name: 'Novice Youth Showmanship', time: '11:00 AM', ring: 'Main Arena', entries: 31 },
    ],
  },
  {
    id: 3,
    name: 'Autumn Gold Futurity',
    startDate: addDays(today, 14),
    endDate: addDays(today, 18),
    location: 'Fort Worth, TX',
    association: 'NRHA',
    status: 'upcoming',
    website: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1551941264-050b71d679d4?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
    patternBook: {
      id: 3,
      isLive: false,
      publishDate: addDays(today, 7),
    },
    totalEntries: 450,
    totalPrizes: '$250,000',
    classes: [],
  },
  {
    id: 4,
    name: 'Annual Color Breed Congress',
    startDate: addDays(today, 30),
    endDate: addDays(today, 35),
    location: 'Tulsa, OK',
    association: 'APHA',
    status: 'upcoming',
    website: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1616346574204-2a021574e94d?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
    patternBook: {
      id: 4,
      isLive: false,
      publishDate: addDays(today, 20),
    },
    totalEntries: 1200,
    totalPrizes: '$1,000,000',
    classes: [],
  },
  {
    id: 5,
    name: 'Winter Circuit Celebration',
    startDate: subDays(today, 20),
    endDate: subDays(today, 15),
    location: 'Scottsdale, AZ',
    association: 'USEF',
    status: 'recent',
    website: 'https://example.com',
    thumbnail: 'https://images.unsplash.com/photo-1557151301-4ff692aa6d3d?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
    patternBook: {
      id: 5,
      isLive: true,
      publishDate: subDays(today, 25),
    },
    totalEntries: 600,
    totalPrizes: '$150,000',
    classes: [],
  },
  {
    id: 6,
    name: 'Ranch Horse Spring Showdown',
    startDate: subDays(today, 45),
    endDate: subDays(today, 43),
    location: 'Guthrie, OK',
    association: 'AQHA',
    status: 'recent',
    website: 'https://example.com',
    thumbnail: null,
    patternBook: null,
    totalEntries: 150,
    totalPrizes: '$15,000',
    classes: [],
  },
];