project_id = "akvmndheosffcgvxuxbr"

[functions.send-pattern-book]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.detect-scoresheet-fields]
verify_jwt = false
