import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { BookOpen, Download, Settings, Zap, Calendar, Search } from 'lucide-react';
import Navigation from '@/components/Navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/components/ui/use-toast';
import { Link } from 'react-router-dom';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger, DialogFooter } from '@/components/ui/dialog';

const PatternBooksPage = () => {
  const [patternBooks, setPatternBooks] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const { toast } = useToast();

  useEffect(() => {
    const savedBooks = localStorage.getItem('equiPatternBooks');
    if (savedBooks) {
      setPatternBooks(JSON.parse(savedBooks));
    } else {
      const sampleBooks = [
        { id: 1, title: 'Complete Breed Show Package (AQHA/APHA/ApHC, etc.)', description: 'Full day western show with 12 patterns across all disciplines.', patterns: 12, disciplines: ['Western Pleasure', 'Reining', 'Trail', 'Showmanship'], price: 250.00, estimatedTime: '8 hours', difficulty: 'Mixed', image: 'Complete western horse show arena with multiple patterns and disciplines', autoGenerated: true, customizable: true },
        { id: 2, title: 'Hunter/Jumper Competitions', description: 'Professional hunter and jumper patterns for championship events.', patterns: 8, disciplines: ['Hunter Under Saddle', 'Hunter Over Fences', 'Jumper'], price: 67.99, estimatedTime: '6 hours', difficulty: 'Advanced', image: 'Hunter jumper arena setup with professional course patterns', autoGenerated: true, customizable: true },
        { id: 3, title: 'Youth Beginner Show', description: 'Safe and educational patterns designed for young riders.', patterns: 6, disciplines: ['Walk-Trot', 'Lead Line', 'Showmanship'], price: 45.99, estimatedTime: '4 hours', difficulty: 'Beginner', image: 'Youth horse show with beginner-friendly patterns and safety focus', autoGenerated: true, customizable: true },
        { id: 4, title: 'Ranch Horse Versatility', description: 'Working ranch horse patterns showcasing versatility.', patterns: 10, disciplines: ['Ranch Riding', 'Ranch Trail', 'Ranch Cutting', 'Ranch Reining'], price: 75.99, estimatedTime: '7 hours', difficulty: 'Intermediate', image: 'Ranch horse versatility patterns in outdoor arena setting', autoGenerated: true, customizable: true }
      ];
      setPatternBooks(sampleBooks);
      localStorage.setItem('equiPatternBooks', JSON.stringify(sampleBooks));
    }
  }, []);

  const filteredBooks = patternBooks.filter(book =>
    book.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    book.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
    book.disciplines.some(discipline => 
      discipline.toLowerCase().includes(searchTerm.toLowerCase())
    )
  );

  const handlePurchase = (book) => {
    toast({
      title: "🚧 This feature isn't implemented yet—but don't worry! You can request it in your next prompt! 🚀",
      description: `Pattern Book: ${book.title} - $${book.price.toFixed(2)}`,
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">Pattern Books</h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Purchase pre-made show packages or use our wizard to auto-generate a compliant, branded book for your entire event.
          </p>
          <Dialog>
            <DialogTrigger asChild>
              <Button size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90">
                <Zap className="h-5 w-5 mr-2" /> Auto-Generate Custom Book
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Pattern Book Generator Wizard</DialogTitle>
                <DialogDescription>This wizard will guide you through creating a complete, compliant pattern book for your show.</DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <Input placeholder="Show Name" />
                <Input type="date" placeholder="Start Date" />
                <Input placeholder="Full Show Address" />
                <p className="text-sm text-muted-foreground">The full wizard will include class selection, sponsor packages, and branding options.</p>
              </div>
              <DialogFooter>
                <Button onClick={() => toast({ title: "🚧 Feature not implemented" })}>Start Building</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.1 }} className="glass-effect rounded-lg p-6 mb-8 border border-border">
          <div className="relative">
             <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground h-5 w-5" />
            <Input placeholder="Search pattern books..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="pl-10 bg-secondary border-border text-foreground placeholder:text-muted-foreground h-12" />
          </div>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {filteredBooks.map((book, index) => (
            <motion.div key={book.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.1 * index }} className="flex">
              <Card className="bg-secondary border-border hover:border-primary/50 transition-all duration-300 group h-full flex flex-col">
                <CardHeader className="pb-4">
                  <div className="aspect-video bg-background rounded-lg mb-4 flex items-center justify-center pattern-grid overflow-hidden">
                    <img-replace alt={book.image} className="w-full h-full object-cover rounded-lg opacity-80 group-hover:scale-105 transition-transform duration-300" />
                  </div>
                  <div className="flex justify-between items-start mb-2">
                    <CardTitle className="text-foreground group-hover:text-primary transition-colors text-xl font-bold">{book.title}</CardTitle>
                    {book.autoGenerated && <Badge className="bg-primary text-primary-foreground"><Zap className="h-3 w-3 mr-1" />Auto-Gen</Badge>}
                  </div>
                  <CardDescription className="mb-4">{book.description}</CardDescription>
                  <div className="flex flex-wrap gap-2">
                    {book.disciplines.slice(0,3).map((discipline) => <Badge key={discipline} variant="outline">{discipline}</Badge>)}
                    {book.disciplines.length > 3 && <Badge variant="outline">+{book.disciplines.length - 3} more</Badge>}
                  </div>
                </CardHeader>
                <CardContent className="flex-grow">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div className="flex items-center text-muted-foreground"><BookOpen className="h-4 w-4 mr-2" />{book.patterns} Patterns</div>
                    <div className="flex items-center text-muted-foreground"><Calendar className="h-4 w-4 mr-2" />{book.estimatedTime}</div>
                    <div className="flex items-center text-muted-foreground">Difficulty: <Badge variant="outline" className="ml-2">{book.difficulty}</Badge></div>
                  </div>
                </CardContent>
                <CardFooter className="pt-4 flex-col items-stretch">
                   <div className="flex justify-between items-center w-full mb-4">
                      <div className="text-3xl font-bold text-foreground">${book.price.toFixed(2)}</div>
                   </div>
                  <div className="flex flex-col gap-2">
                    <Button onClick={() => handlePurchase(book)} className="w-full bg-primary text-primary-foreground hover:bg-primary/90">
                      <Download className="h-4 w-4 mr-2" /> Purchase Book
                    </Button>
                    {book.customizable && (
                      <Button asChild variant="outline" className="w-full">
                        <Link to={`/customize/${book.id}`}><Settings className="h-4 w-4 mr-2" />Customize & Brand</Link>
                      </Button>
                    )}
                  </div>
                </CardFooter>
              </Card>
            </motion.div>
          ))}
        </div>

        {filteredBooks.length === 0 && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-20">
            <div className="text-muted-foreground text-2xl font-semibold">No pattern books found.</div>
            <p className="text-muted-foreground/80 mt-2">Try adjusting your search or create your own with Auto-Generate!</p>
          </motion.div>
        )}
      </div>
    </div>
  );
};

export default PatternBooksPage;