-- Insert APHA disciplines for Open Shows association
INSERT INTO disciplines (name, association_id, pattern_type, category, sort_order, open_divisions) VALUES
('Showmanship at Halter', 'open-show', 'pattern', 'Halter', 1, true),
('Reining', 'open-show', 'pattern', 'Reining', 2, true),
('Working Cow Horse', 'open-show', 'pattern', 'Cattle', 3, true),
('Heading', 'open-show', NULL, 'Cattle', 4, true),
('Heeling', 'open-show', NULL, 'Cattle', 5, true),
('Tie-Down Roping', 'open-show', NULL, 'Cattle', 6, true),
('Breakaway Roping', 'open-show', NULL, 'Cattle', 7, true),
('Steer Stopping', 'open-show', NULL, 'Cattle', 8, true),
('Team Penning', 'open-show', NULL, 'Cattle', 9, true),
('Ranch Sorting', 'open-show', NULL, 'Cattle', 10, true),
('Cutting', 'open-show', 'pattern', 'Cattle', 11, true),
('Western Pleasure', 'open-show', NULL, 'Rail', 12, true),
('Hunter Under Saddle', 'open-show', NULL, 'Rail', 13, true),
('Western Riding', 'open-show', 'pattern', 'Pattern', 14, true),
('Trail', 'open-show', 'pattern', 'Pattern', 15, true),
('Ranch Riding', 'open-show', 'pattern', 'Ranch', 16, true),
('Ranch Trail', 'open-show', 'pattern', 'Ranch', 17, true),
('Ranch Cutting', 'open-show', 'pattern', 'Ranch', 18, true),
('Ranch Cow Work', 'open-show', 'pattern', 'Ranch', 19, true),
('Ranch Conformation', 'open-show', NULL, 'Ranch', 20, true),
('Barrel Racing', 'open-show', 'pattern', 'Speed', 21, true),
('Pole Bending', 'open-show', 'pattern', 'Speed', 22, true),
('Stake Race', 'open-show', 'pattern', 'Speed', 23, true),
('Hunt Seat Equitation', 'open-show', 'pattern', 'English', 24, true),
('Western Horsemanship', 'open-show', 'pattern', 'Pattern', 25, true),
('Longe Line', 'open-show', 'pattern', 'Halter', 26, true),
('Jumping', 'open-show', NULL, 'English', 27, true),
('Working Hunter', 'open-show', NULL, 'English', 28, true),
('Versatility Ranch Horse', 'open-show', 'pattern', 'Ranch', 29, true);