// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akvmndheosffcgvxuxbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdm1uZGhlb3NmZmNndnh1eGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODU0NzEsImV4cCI6MjA3MzE2MTQ3MX0.ZEPNWFq_3jK1RcG3TzIAq2Q7KnTiyzLEa0Tj_siFlL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});